#!/usr/bin/env bash
# =============================================================================
# nginx.sh — Nginx reverse proxy configuration and SSL setup
# =============================================================================
# Usage (standalone):
#   sudo ./scripts/nginx.sh config.yaml
#
# Or called automatically by deploy.sh.
#
# What it does:
#   1. Reads domain, port, ssl_mode, and config name from config.yaml
#   2. Generates an Nginx server block (HTTP redirect + HTTPS + proxy_pass)
#   3. Writes it to /etc/nginx/sites-available/<nginx_config_name>
#   4. Creates a symlink in sites-enabled/
#   5. Tests the Nginx configuration with nginx -t
#   6. Handles SSL:
#      - cloudflare: expects cert/key already in place, validates paths
#      - certbot:    runs certbot --nginx to obtain and install a cert
#   7. Reloads Nginx
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/utils.sh"

# ─────────────────────────────────────────────────────────────────────────────
# Validate input
# ─────────────────────────────────────────────────────────────────────────────

if [[ $# -lt 1 ]]; then
    echo "Usage: sudo $0 config.yaml"
    exit 1
fi

CONFIG_FILE="$1"
require_root
require_commands nginx

# ─────────────────────────────────────────────────────────────────────────────
# Load config values
# ─────────────────────────────────────────────────────────────────────────────

DOMAIN="$(yaml_get        "domain"             "$CONFIG_FILE")"
PORT="$(yaml_get          "port"               "$CONFIG_FILE")"
NGINX_NAME="$(yaml_get    "nginx_config_name"  "$CONFIG_FILE")"
SSL_MODE="$(yaml_get      "ssl_mode"           "$CONFIG_FILE")"
LOG_DIR="$(yaml_get       "log_dir"            "$CONFIG_FILE")"

# Certbot email only needed when ssl_mode=certbot
CERTBOT_EMAIL=""
if [[ "$SSL_MODE" == "certbot" ]]; then
    CERTBOT_EMAIL="$(yaml_get "certbot_email" "$CONFIG_FILE")"
fi

DEPLOY_LOG="${LOG_DIR}/deploy.log"
ensure_log_dir

NGINX_AVAILABLE="/etc/nginx/sites-available/${NGINX_NAME}"
NGINX_ENABLED="/etc/nginx/sites-enabled/${NGINX_NAME}"
CERT_PATH="/etc/ssl/certs/${NGINX_NAME}.crt"
KEY_PATH="/etc/ssl/private/${NGINX_NAME}.key"

log_step "Nginx configuration — domain: $DOMAIN | ssl_mode: $SSL_MODE"

# ─────────────────────────────────────────────────────────────────────────────
# Step 1 — Generate Nginx server block
# ─────────────────────────────────────────────────────────────────────────────

log_step "Generating Nginx server block"

# Decide certificate paths based on ssl_mode
if [[ "$SSL_MODE" == "cloudflare" ]]; then
    SSL_CERT_LINE="ssl_certificate     ${CERT_PATH};"
    SSL_KEY_LINE="ssl_certificate_key ${KEY_PATH};"
elif [[ "$SSL_MODE" == "certbot" ]]; then
    # Certbot manages these paths; we use placeholders that certbot replaces
    SSL_CERT_LINE="# ssl_certificate — managed by Certbot"
    SSL_KEY_LINE="# ssl_certificate_key — managed by Certbot"
fi

cat > "$NGINX_AVAILABLE" << NGINX_CONF
# ─────────────────────────────────────────────────────────────────────────────
# Digit Recognizer API — Nginx configuration
# Generated by nginx.sh on $(date '+%Y-%m-%d %H:%M:%S')
# Domain : ${DOMAIN}
# Backend: localhost:${PORT}
# SSL    : ${SSL_MODE}
# ─────────────────────────────────────────────────────────────────────────────

# Redirect all HTTP traffic to HTTPS
server {
    listen 80;
    server_name ${DOMAIN};
    return 301 https://\$host\$request_uri;
}

# HTTPS server with reverse proxy to Docker container
server {
    listen 443 ssl;
    server_name ${DOMAIN};

    # ── SSL ──────────────────────────────────────────────────────────────── #
    ${SSL_CERT_LINE}
    ${SSL_KEY_LINE}

    ssl_protocols             TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers               'ECDH+AESGCM:ECDH+AES256:ECDH+AES128:!aNULL:!MD5:!DSS';
    ssl_session_cache         shared:SSL:10m;
    ssl_session_timeout       10m;

    # ── Security headers ─────────────────────────────────────────────────── #
    add_header X-Frame-Options      "SAMEORIGIN"    always;
    add_header X-Content-Type-Options "nosniff"     always;
    add_header X-XSS-Protection     "1; mode=block" always;
    add_header Referrer-Policy      "no-referrer"   always;

    # ── Logging ──────────────────────────────────────────────────────────── #
    access_log /var/log/nginx/${NGINX_NAME}.access.log;
    error_log  /var/log/nginx/${NGINX_NAME}.error.log;

    # ── Reverse proxy to Docker container ───────────────────────────────── #
    location / {
        proxy_pass         http://localhost:${PORT};
        proxy_http_version 1.1;

        # Forward real client information
        proxy_set_header Host              \$host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;

        # Timeouts
        proxy_connect_timeout 10s;
        proxy_read_timeout    30s;
        proxy_send_timeout    10s;
    }
}
NGINX_CONF

log_success "Server block written to $NGINX_AVAILABLE"

# ─────────────────────────────────────────────────────────────────────────────
# Step 2 — Enable the site
# ─────────────────────────────────────────────────────────────────────────────

log_step "Enabling site in sites-enabled"

if [[ -L "$NGINX_ENABLED" ]]; then
    log_warn "Symlink already exists at $NGINX_ENABLED — removing and re-creating"
    rm "$NGINX_ENABLED"
fi

ln -s "$NGINX_AVAILABLE" "$NGINX_ENABLED"
log_success "Symlink created: $NGINX_ENABLED"

# ─────────────────────────────────────────────────────────────────────────────
# Step 3 — Handle SSL
# ─────────────────────────────────────────────────────────────────────────────

log_step "Configuring SSL (mode: $SSL_MODE)"

if [[ "$SSL_MODE" == "cloudflare" ]]; then
    # Validate that the certificate and key files exist
    if [[ ! -f "$CERT_PATH" ]]; then
        log_error "Cloudflare origin certificate not found at: $CERT_PATH"
        log_error "Download it from Cloudflare Dashboard → SSL/TLS → Origin Server"
        log_error "Then place it at: $CERT_PATH"
        exit 1
    fi

    if [[ ! -f "$KEY_PATH" ]]; then
        log_error "Cloudflare origin key not found at: $KEY_PATH"
        log_error "Download it from Cloudflare Dashboard → SSL/TLS → Origin Server"
        log_error "Then place it at: $KEY_PATH"
        exit 1
    fi

    chmod 600 "$KEY_PATH"
    log_success "Cloudflare SSL: certificate and key found and secured"

elif [[ "$SSL_MODE" == "certbot" ]]; then
    if ! command -v certbot &>/dev/null; then
        log_info "Installing Certbot..."
        apt-get install -y -qq certbot python3-certbot-nginx
    fi

    log_info "Running Certbot for $DOMAIN..."
    certbot --nginx \
        --non-interactive \
        --agree-tos \
        --email "$CERTBOT_EMAIL" \
        -d "$DOMAIN"

    log_success "Certbot: certificate obtained and installed for $DOMAIN"

    # Verify auto-renewal
    certbot renew --dry-run --quiet
    log_success "Certbot: auto-renewal dry-run passed"

else
    log_error "Unknown ssl_mode: '$SSL_MODE' — must be 'cloudflare' or 'certbot'"
    exit 1
fi

# ─────────────────────────────────────────────────────────────────────────────
# Step 4 — Test configuration and reload
# ─────────────────────────────────────────────────────────────────────────────

log_step "Testing Nginx configuration"
nginx -t
log_success "Nginx configuration syntax is valid"

log_step "Reloading Nginx"
systemctl reload nginx
log_success "Nginx reloaded"

systemctl is-active nginx && log_success "Nginx is running" || {
    log_error "Nginx is not running after reload"
    exit 1
}

# ─────────────────────────────────────────────────────────────────────────────
# Done
# ─────────────────────────────────────────────────────────────────────────────

echo ""
log_success "════════════════════════════════════════════════════"
log_success "  Nginx configuration complete"
log_success "  Domain  : https://${DOMAIN}"
log_success "  Backend : localhost:${PORT}"
log_success "  SSL     : ${SSL_MODE}"
log_success "  Config  : ${NGINX_AVAILABLE}"
log_success "════════════════════════════════════════════════════"
